
export type Product = {
  id: string;
  title: string;
  category: string;
  subcategory: string;
  topic: string;
  scale: string;
  price: number;
  year: number;
  image: string;
  isNew?: boolean;
  inStock: boolean;
};

export const products: Product[] = [
  {
    id: "1",
    title: "F-14D Super Tomcat 'Grim Reapers'",
    category: "Aircraft",
    subcategory: "Jets",
    topic: "F-14 Tomcat",
    scale: "1:48",
    price: 89.99,
    year: 2023,
    image: "/images/products/f14_tomcat_model.png",
    isNew: true,
    inStock: true,
  },
  {
    id: "2",
    title: "M1A2 SEPv3 Abrams",
    category: "Armor",
    subcategory: "Tanks",
    topic: "M1 Abrams",
    scale: "1:35",
    price: 74.50,
    year: 2022,
    image: "/images/products/m1a2_abrams_model.png",
    inStock: true,
  },
  {
    id: "3",
    title: "U.S.S. Enterprise CVN-65",
    category: "Ships",
    subcategory: "Aircraft Carriers",
    topic: "USS Enterprise",
    scale: "1:350",
    price: 210.00,
    year: 2020,
    image: "/images/products/uss_enterprise_model.png",
    inStock: false,
  },
  {
    id: "4",
    title: "Saturn V Rocket",
    category: "Space",
    subcategory: "Rockets",
    topic: "Saturn V",
    scale: "1:144",
    price: 129.95,
    year: 2019,
    image: "/images/products/saturn_v_model.png",
    isNew: true,
    inStock: true,
  },
  {
    id: "5",
    title: "Spitfire Mk.IXc",
    category: "Aircraft",
    subcategory: "Propeller",
    topic: "Supermarine Spitfire",
    scale: "1:32",
    price: 115.00,
    year: 2024,
    image: "/images/products/spitfire_model.png",
    inStock: true,
  },
  {
    id: "6",
    title: "Tiger I Late Production",
    category: "Armor",
    subcategory: "Tanks",
    topic: "Tiger I",
    scale: "1:35",
    price: 68.99,
    year: 2021,
    image: "/images/products/tiger_tank_model.png",
    inStock: true,
  },
  {
    id: "7",
    title: "Yamato Battleship",
    category: "Ships",
    subcategory: "Battleships",
    topic: "Yamato",
    scale: "1:700",
    price: 45.00,
    year: 2018,
    image: "/images/products/yamato_battleship_model.png",
    inStock: true,
  },
  {
    id: "8",
    title: "X-Wing Starfighter",
    category: "Sci-Fi",
    subcategory: "Star Wars",
    topic: "X-Wing",
    scale: "1:72",
    price: 34.99,
    year: 2022,
    image: "/images/products/xwing_model.png",
    inStock: true,
  },
  {
    id: "9",
    title: "P-51D Mustang 'Big Beautiful Doll'",
    category: "Aircraft",
    subcategory: "Propeller",
    topic: "P-51 Mustang",
    scale: "1:48",
    price: 54.99,
    year: 2020,
    image: "/images/products/p51d_mustang_model.png",
    inStock: true,
  },
  {
    id: "10",
    title: "T-34/85 Soviet Medium Tank",
    category: "Armor",
    subcategory: "Tanks",
    topic: "T-34",
    scale: "1:35",
    price: 49.99,
    year: 2023,
    image: "/images/products/t34_85_tank_model.png",
    isNew: true,
    inStock: true,
  },
  {
    id: "11",
    title: "YT-1300 Millennium Falcon",
    category: "Sci-Fi",
    subcategory: "Star Wars",
    topic: "Millennium Falcon",
    scale: "1:144",
    price: 149.95,
    year: 2021,
    image: "/images/products/millennium_falcon_model.png",
    inStock: false,
  },
  {
    id: "12",
    title: "RMS Titanic Centenary Edition",
    category: "Ships",
    subcategory: "Ocean Liners",
    topic: "Titanic",
    scale: "1:700",
    price: 59.99,
    year: 2012,
    image: "/images/products/titanic_ship_model.png",
    inStock: true,
  },
  // Bestsellers from Home Page
  {
    id: "101",
    title: "T-800 Endoskeleton Bust",
    category: "Sci-Fi",
    subcategory: "Terminator",
    topic: "T-800",
    scale: "1:1",
    price: 249.99,
    year: 2023,
    image: "/bestseller-t800.png",
    inStock: true,
    isNew: false,
  },
  {
    id: "102",
    title: "F-14 Tomcat 'Maverick'",
    category: "Aircraft",
    subcategory: "Jets",
    topic: "F-14 Tomcat",
    scale: "1:48",
    price: 99.99,
    year: 2022,
    image: "/bestseller-f14.png",
    inStock: true,
    isNew: false,
  },
  {
    id: "103",
    title: "Atlas Titan Model",
    category: "Sci-Fi",
    subcategory: "Mechs",
    topic: "Titanfall",
    scale: "1:60",
    price: 189.99,
    year: 2021,
    image: "/bestseller-titan.png",
    inStock: true,
    isNew: false,
  },
  {
    id: "104",
    title: "Cyberpunk Racer 2077",
    category: "Vehicles",
    subcategory: "Cars",
    topic: "Cyberpunk 2077",
    scale: "1:18",
    price: 79.99,
    year: 2020,
    image: "/bestseller-cyberpunk.png",
    inStock: true,
    isNew: false,
  },
  {
    id: "105",
    title: "Spitfire Mk. IX",
    category: "Aircraft",
    subcategory: "Propeller",
    topic: "Supermarine Spitfire",
    scale: "1:48",
    price: 85.00,
    year: 2023,
    image: "/bestseller-spitfire.png",
    inStock: true,
    isNew: false,
  },
  // Latest Models from Home Page
  {
    id: "201",
    title: "XV-9 Heavy Assault Mech",
    category: "Sci-Fi",
    subcategory: "Mechs",
    topic: "Warhammer 40k",
    scale: "1:60",
    price: 129.99,
    year: 2024,
    image: "/latest-mech.png",
    inStock: true,
    isNew: true,
  },
  {
    id: "202",
    title: "P-51 Mustang 'Old Crow'",
    category: "Aircraft",
    subcategory: "Propeller",
    topic: "P-51 Mustang",
    scale: "1:48",
    price: 89.99,
    year: 2023,
    image: "/latest-p51.png",
    inStock: true,
    isNew: false, 
  },
  {
    id: "203",
    title: "Aurora GP-X Racer",
    category: "Sci-Fi",
    subcategory: "Cars",
    topic: "F-Zero",
    scale: "1:24",
    price: 149.99,
    year: 2024,
    image: "/latest-racer.png",
    inStock: true,
    isNew: true,
  },
];

export const categories = ["All", "Aircraft", "Armor", "Ships", "Space", "Sci-Fi", "Vehicles"];
export const subcategories = ["All", "Jets", "Propeller", "Tanks", "Aircraft Carriers", "Battleships", "Ocean Liners", "Rockets", "Star Wars", "Mechs", "Cars", "Terminator"];
export const scales = ["All", "1:144", "1:72", "1:48", "1:35", "1:32", "1:700", "1:350", "1:24", "1:18", "1:1"];
